### ISSUE TITLE
Latest version of Logestic still not running with Elysia 1.1.3

### ISSUE THREAD

**Issue by Ripwords** [cybercoder-naj/logestic#33]
### What version of Logestic are you using?

v1.2.1

### What is the bug and how to reproduce it?

Install Logestic v1.2.1 with an Elysia 1.1.3 project, run dev, and elysia doesn't run

### What is the expected behaviour?

Elysia runs with Logestic

### Any additional information/media?

1. Runs with Logestic using preview folder from this repo i forked
![image](https://github.com/user-attachments/assets/8a52ea6d-377c-4cba-bd0e-d7c867c5c61f)

2. Running without Logestic 
![image](https://github.com/user-attachments/assets/adc98c71-54a5-4828-8b31-fcb5bde95ac0)

**Comment by cybercoder-naj** [comment]
I experienced this last night as well. If you copy over the files as-is, Elysia runs. I suspect `bun build` is causing an issue. It is strange since I have no clue where it error is coming from (as of today). There are no such major changes in #32 that could cause this. I'll research and investigate over the weekend. If you find something as well, feel free to drop it in here/open a PR.

**Comment by cybercoder-naj** [comment]
Edit, the `--minify` flag of `bun build` has some error.

**Comment by Ripwords** [comment]
https://bun.sh/docs/bundler#minify

Using the granular minification configuration I've identified that the cause is `--minify-identifiers` as adding `--minify-whitespace` and `--minify-syntax` both allows for a build that runs successfully

**Comment by Ripwords** [comment]
Possibly related to https://github.com/oven-sh/bun/issues/9474
